# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='姓名')),
                ('author_name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文姓名')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_create_time', models.DateTimeField(auto_created=True, verbose_name='添加时间')),
                ('book_isbn', models.CharField(max_length=20, verbose_name='ISBN')),
                ('book_name', models.CharField(max_length=200, verbose_name='书名')),
                ('book_retail_price', models.FloatField(verbose_name='定价')),
                ('book_pub_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='出版日期')),
                ('book_imageurl', models.URLField(verbose_name='图片')),
                ('book_binding', models.CharField(blank=True, max_length=25, null=True, verbose_name='装帧')),
                ('book_douban_score', models.FloatField(blank=True, null=True, verbose_name='豆瓣评分')),
                ('book_author', models.ManyToManyField(blank=True, null=True, to='goldbook.Author', verbose_name='作者')),
            ],
            options={
                'verbose_name': '书',
                'verbose_name_plural': '书',
            },
        ),
        migrations.CreateModel(
            name='Eplatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_code', models.CharField(max_length=5, verbose_name='平台代码')),
                ('plat_name', models.CharField(max_length=20, verbose_name='平台名称')),
            ],
            options={
                'verbose_name': '电商平台',
                'verbose_name_plural': '电商平台',
            },
        ),
        migrations.CreateModel(
            name='PlatBookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_price', models.FloatField(blank=True, default=0, null=True, verbose_name='平台价格')),
                ('book_url', models.URLField(blank=True, null=True, verbose_name='商品链接')),
                ('book_update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldbook.Book')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldbook.Eplatform')),
            ],
            options={
                'verbose_name': '价格信息',
                'verbose_name_plural': '价格信息',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=200, verbose_name='出版社名称')),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='book_pub',
            field=models.ManyToManyField(blank=True, null=True, to='goldbook.Publisher', verbose_name='出版社'),
        ),
    ]
