# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_create_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='添加时间'),
        ),
    ]
