# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbook', '0002_auto_20171121_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.ManyToManyField(blank=True, to='goldbook.Author', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_pub',
            field=models.ManyToManyField(blank=True, to='goldbook.Publisher', verbose_name='出版社'),
        ),
    ]
