# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbook', '0002_auto_20171123_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_binding',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='装帧'),
        ),
    ]
