# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbook', '0003_auto_20171123_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_pub_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='出版日期'),
        ),
    ]
