# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbook', '0004_book_book_douban_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='platbookinfo',
            name='product_id',
            field=models.CharField(default=1, max_length=50, verbose_name='商品编号'),
            preserve_default=False,
        ),
    ]
