# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goldbook', '0005_platbookinfo_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eplatform',
            name='plat_icon',
            field=models.ImageField(default=2, upload_to='', verbose_name='图标'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platbookinfo',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldbook.Book', verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='platbookinfo',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldbook.Eplatform', verbose_name='平台'),
        ),
    ]
