# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbook', '0006_auto_20171123_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_am',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('am_isbn', models.CharField(blank=True, max_length=50, null=True, validators=['I', 'S', 'B', 'N'])),
                ('am_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='书名')),
                ('am_pub', models.CharField(blank=True, max_length=200, null=True, verbose_name='出版信息')),
                ('am_kindle', models.BooleanField(default=False, verbose_name='Kindle')),
                ('am_uti_kindle', models.BooleanField(default=False, verbose_name='Kindle Unlimited')),
                ('am_kindle_pirce', models.FloatField(blank=True, null=True, verbose_name='Kindle价格')),
                ('am_paper_price', models.FloatField(blank=True, null=True, verbose_name='纸质价格')),
                ('am_type', models.IntegerField(blank=True, null=True, verbose_name='装帧')),
            ],
            options={
                'verbose_name': 'am书',
                'verbose_name_plural': 'am书',
            },
        ),
    ]
