# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goldbook', '0007_book_am'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_url', models.URLField(verbose_name='URL')),
                ('handle_stat', models.IntegerField(choices=[(1, '等待'), (2, '下载中'), (3, '完成'), (4, '异常')], verbose_name='处理状态')),
                ('handle_time', models.DateTimeField(auto_now=True, verbose_name='处理时间')),
                ('handle_message', models.TextField(verbose_name='处理结果')),
                ('web_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldbook.Eplatform', verbose_name='平台')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URL',
            },
        ),
        migrations.AlterField(
            model_name='book_am',
            name='am_type',
            field=models.IntegerField(blank=True, choices=[(1, '平装'), (2, '精装'), (2, 'Kindle')], null=True, verbose_name='装帧'),
        ),
    ]
