# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbook', '0008_auto_20171128_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmanager',
            name='handle_message',
            field=models.TextField(blank=True, null=True, verbose_name='处理结果'),
        ),
        migrations.AlterField(
            model_name='urlmanager',
            name='handle_stat',
            field=models.IntegerField(choices=[(0, '初始'), (1, '等待'), (2, '下载中'), (3, '完成'), (4, '异常')], default=0, verbose_name='处理状态'),
        ),
    ]
